In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [28]:
data=pd.read_csv('spam_ham_dataset.csv')

In [29]:
data.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [30]:
data.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5171 non-null   int64 
 1   label       5171 non-null   object
 2   text        5171 non-null   object
 3   label_num   5171 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 161.7+ KB


In [32]:
from sklearn.preprocessing import LabelEncoder
label_enco=LabelEncoder()

In [33]:
label_enco.fit(data['text'])

LabelEncoder()

In [34]:
label_enco.transform(data['text'])

array([1209, 1985, 2774, ...,  495, 2223, 2195])

In [35]:
data['text']=label_enco.transform(data['text'])

In [36]:
data.head()

Unnamed: 0 label  text  label_num
0         605   ham  1209          0
1        2349   ham  1985          0
2        3624   ham  2774          0
3        4685  spam  3158          1
4        2030   ham  3613          0

In [40]:
from sklearn.preprocessing import OneHotEncoder
one_hot=OneHotEncoder()

In [41]:
one_hot.fit(data[['label']])

OneHotEncoder()

In [42]:

arr_label =one_hot.transform(data[['label']]).toarray()
arr_label

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [43]:
label_cols=one_hot.categories_
label_cols

[array(['ham', 'spam'], dtype=object)]

In [44]:
label=pd.DataFrame(arr_label,columns=['ham', 'spam'],dtype='int')

In [45]:
label.head()

ham  spam
0    1     0
1    1     0
2    1     0
3    0     1
4    1     0

In [46]:
data= pd.concat([label,data],axis=1)

In [48]:
data.drop('label',axis=1,inplace=True)

In [50]:
data.columns

Index(['ham', 'spam', 'Unnamed: 0', 'text', 'label_num'], dtype='object')

In [51]:
X = data[['ham', 'spam', 'Unnamed: 0', 'text']]
Y = data['label_num']

In [61]:
from sklearn.model_selection import train_test_split  #complusary

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=101)

In [62]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()

In [63]:
X_test

ham  spam  Unnamed: 0  text
1039    1     0        3473  4646
893     1     0        2290  1878
4616    0     1        4877  4342
1905    0     1        4817  2151
2026    1     0         698  4288
...   ...   ...         ...   ...
778     0     1        4149  4067
2231    1     0        2384  4218
4540    0     1        4991  1588
1860    0     1        4057  3255
427     1     0        2754   377

[1035 rows x 4 columns]

In [64]:
X_test.iloc[0]

ham              1
spam             0
Unnamed: 0    3473
text          4646
Name: 1039, dtype: int64

In [69]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()


In [70]:
model.predict(X_test)

array([0, 0, 1, ..., 1, 1, 0], dtype=int64)

In [71]:
logistic.fit(X_train,Y_train)

LogisticRegression()

In [72]:
predictions=logistic.predict(X_test)

In [73]:
from sklearn.metrics import confusion_matrix, classification_report

In [74]:
print(confusion_matrix(predictions,Y_test))

[[735   0]
 [  0 300]]


In [75]:
print(classification_report(predictions,Y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       735
           1       1.00      1.00      1.00       300

    accuracy                           1.00      1035
   macro avg       1.00      1.00      1.00      1035
weighted avg       1.00      1.00      1.00      1035



TypeError: got an unexpected keyword argument 'annot'